name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
            
    - name: Build and push
      run: | 
        echo ---Building and starting up docker---
        docker-compose -f docker-compose.yml -p bullet_journal_up build
        docker-compose push foodawn/msi_docker_hub
        echo ---Containers up---
 
